server:
  port: ${PORT}
spring:
  profiles:
    active: ${PROFILE}

  data:
    mongodb:
      uri: ${DATABASE_URL}
app:
  auth:
    ignorePaths: /**,/article/**
  read-time:
    config:
      bytes-by-word: ${BYTES_BY_WORD}
      words-by-minute: ${WORD_BY_MINUTE}
  security:
    header: ${HEADER_NAME}
    authorization: ${SHARED_SECRET}

aws:
  endpoint: ${AWS_ENDPOINT}
  region: ${AWS_REGION}
  buckets:
    article-bucket: ${ARTICLE_BUCKET}

logging:
  level:
    root: WARN
    com:
      server:
        taxco: TRACE
