server:
  port: ${PORT}
spring:
  profiles:
    active: ${PROFILE}
  security:
    user:
      name: taxco
      password: ${SHARED_SECRET}
  data:
    mongodb:
      uri: ${DATABASE_URL}
app:
  auth:
    ignorePaths: /**,/article/**

aws:
  endpoint: ${AWS_ENDPOINT}
  region: ${AWS_REGION}
  buckets:
    article-bucket: ${ARTICLE_BUCKET}

logging:
  level:
    root: WARN
    com:
      server:
        taxco: TRACE
