import { PageType } from "../../data/constants";
import { Header } from "../../components/Header";
import MarkdownFormatter from "../../components/MarkdownFormatter";
import { Image, Text, VStack } from "@chakra-ui/react";
import EX from "../../assets/Markdown/ex.md";
import { importLocalMarkdownFile } from "../../hooks/useFileUtils";
import { TopicTag } from "../../components/TopicTag";
import { SampleCard } from "../../components/SampleCard";

export function Post() {
  const content = importLocalMarkdownFile(EX);

  return (
    <>
      <Header type={PageType.DEFAULT} />
      <main className="main space-y-6 px-0">
        <VStack spacing={1}>
          <Image
            src="https://th.bing.com/th/id/OIG.dkD1meYhDHXfRc6PlsNr?pid=ImgGn"
            alt="A big octopus managing containers"
            objectFit="cover"
          />
          <Text fontSize={"xs"} color={"GrayText"}>
            Image generated by Bing
          </Text>
        </VStack>
        <div className="flex-col space-y-5 px-6">
          {/* Titulo */}
          <Text fontSize={"2xl"} fontWeight={"semibold"}>
            Introdução ao Kubernetes: Orquestração de Contâiners
          </Text>
          <TopicTag color="red" variant="solid" title="Art" />
          <MarkdownFormatter text={content} />

          <Text fontSize={"2xl"} pt={8}>
            Related Posts
          </Text>

          <SampleCard />
        </div>
      </main>
    </>
  );
}
