import { Image, Text, VStack } from "@chakra-ui/react";
import api from "../../http/api"

export function ImageBlock({articleId} : {articleId : string}) {

  return (
    <VStack spacing={1} p={0}>
      <Image
        src={`${api.defaults.baseURL}/article/${articleId}/image`}
        alt={articleId}
        objectFit="cover"
        // maxH={"500px"}
      />
      <Text fontSize={"xs"} color={"GrayText"}>
         @Bing: generated by Bing
      </Text>
    </VStack>
  );
}
