import { Image, Text, VStack } from "@chakra-ui/react";

export function ImageBlock() {
  return (
    <VStack spacing={1} p={0}>
      <Image
        src="https://th.bing.com/th/id/OIG.dkD1meYhDHXfRc6PlsNr?pid=ImgGn"
        alt="A big octopus managing containers"
        objectFit="cover"
      />
      <Text fontSize={"xs"} color={"GrayText"}>
        Image generated by Bing
      </Text>
    </VStack>
  );
}
